In [1]:
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
import numpy as np

In [2]:
url='https://chipublib.bibliocommons.com/events/rss/all'
program_list={}
my_dict = {"program_name":[],
           "program_description":[],
           "program_url":[],
           "virtual":[],
           "registration_url":[],
           "start_date":[],
           "end_date":[],
           "program":[],
           "category":[],
          "audience":[],
          "language":[],
          "location_name":[],
          "location_address":[],
          "location_city":[],
          "location_state":[],
          "location_zip":[],
          "contact_name":[],
          "contact_phone":[],
          "contact_email":[]}

In [3]:
r=requests.get(url)
soup=bs(r.text, features='xml')
#         return print('CPL scrape successful: ',r.status_code)
programs=soup.find_all('item')

In [4]:
for p in programs:
            title=p.find('title').text
            description=p.find('description').text.strip()
            link=p.find('link').text
            virtual=p.find('bc:is_virtual').text
            start_date=p.find('bc:start_date_local').text
            end_date=p.find('bc:end_date_local').text
            program=getattr(p.find('category',domain='Program'), 'text', 'null')
            category=getattr(p.find('category',domain='Type'), 'text', 'null')
            audience=p.find_all('category',domain='Audience')
            language=p.find_all('category',domain='Language')
            location=p.find_all('bc:location')
            if location is not None:
                for l in location:
                    location_name=getattr(l.find('bc:name'), 'string', None)
                
            location_number=getattr(p.find('bc:number'), 'string', 'null')
            location_street=getattr(p.find('bc:street'), 'string', 'null')
            location_address=f'{location_number} {location_street}'
            location_city=getattr(p.find('bc:city'), 'string', 'null')
            location_zip=getattr(p.find('bc:zip'), 'string', 'null')
            location_state=getattr(p.find('bc:state'), 'string', 'null')
            contact_name=p.find('bc:contact')
            contact_phone=getattr(p.find('bc:phone'), 'string', 'null')
            contact_email=getattr(p.find('bc:email'), 'string', 'null')
            
            
            my_dict["program_name"].append(title)
            my_dict["program_description"].append(description)
            my_dict["program_url"].append(link)
            my_dict["registration_url"].append(link)
            my_dict["virtual"].append(virtual)
            my_dict["start_date"].append(start_date)
            my_dict["end_date"].append(start_date)
            my_dict["program"].append(program)
            my_dict["category"].append(category)
            my_dict["audience"].append(audience)
            my_dict["language"].append(language)
            my_dict["location_name"].append(location_name)
            my_dict["location_address"].append(location_address)
            my_dict["location_city"].append(location_city)
            my_dict["location_state"].append(location_state)
            my_dict["location_zip"].append(location_zip)
            my_dict["contact_name"].append(contact_name)
            my_dict["contact_phone"].append(contact_phone)
            my_dict["contact_email"].append(contact_email)
            
#             program={'title':title,
#                     'link':link,
#                     'start date':start_date
#                     }
#             program_list.append(program)

In [5]:
df = pd.DataFrame(my_dict)
df.head(30)

program_name  \
0                       Grab and Go: Paper Rose Craft   
1                                        Toddler Time   
2                                        Book Zoomies   
3   The Art of Storytelling with Pixar: In Person ...   
4                                Preschool Story Time   
5                          Story Time with Ms. Jessie   
6      Preschool Story Time with Budlong Woods Branch   
7                     Fall Story Time with Ms. Sharon   
8   Research Your Family History with the Polish G...   
9                           Story Time with Mr. James   
10                   Grab and Go: Wianek Flower Crown   
11  Information Session on Careers in Welding and ...   
12    Adult Book Discussion: And Then There Were None   
13                    Tech Thursdays @ Beverly Branch   
14                                          Teen Zone   
15                                After School Meals    
16                                After School Meals    
17                                        Zine Making   
18                                After School Meals    
19                             Tic Tac Toe Tournament   
20              How to Zoom: Intro to Online Meetings   
21     YOUmedia Stitch Session - Sewing Certification   
22                         Reading Buddies: Beginners   
23               Family Craft and Story with Mr. Omar   
24              Create Club with Budlong Woods Branch   
25                                     Bangin' Beats    
26                               When Your Pen Speaks   
27                            Haunted Chicago History   
28                       Reading Buddies: Independent   
29                                     PreK STEAM Day   

                                  program_description  \
0   <p>In celebration of Latinx History Month come...   
1   <p>Join the staff of the Thomas Hughes Childre...   
2   <p>Book Zoomies presents funny books, silly so...   
3   <p><strong>THE ART </strong>OF STORYTELLING LE...   
4   <p>Ms. April from the Blackstone Branch will s...   
5   <p>Join Ms. Jessie of the Rogers Park Branch f...   
6   <p>Join us for fun stories, songs&nbsp;and a c...   
7   <p>Join Ms. Sharon from the&nbsp;Dunning Branc...   
8   <figure><a href="https://pgsa.org/" target="_b...   
9   <p>Join Mr. James from the Edgebrook Branch as...   
10  <p>Celebrate Polish American Heritage Month by...   
11  <figure><img src="https://chipublib.bibliocomm...   
12  <p>Join King Branch&nbsp;for&nbsp;a discussion...   
13  <p>Are you a computer novice or regular user i...   
14  <p>Come join us in the community room after sc...   
15  <p>Free after school meals are provided by the...   
16  <p>Free after school meals are provided by the...   
17  <p>A zine is a hand-made magazine. Kids will u...   
18  <p>Free after school meals are provided by the...   
19  <p>Come and join a Tic Tac Toe&nbsp;tournament...   
20  <p>Have you been invited to a Zoom meeting, or...   
21  <p>Join our sewing workshop where you can lear...   
22  <p>Do you need practice with your reading skil...   
23  <p>Gather the family and join us for a themed ...   
24  <p>Join us for&nbsp;a fun, hands-on&nbsp;activ...   
25  <p>Turn your beats and bars into songs. Virtua...   
26  <p>Spoken word poetry is a word-based performa...   
27  <p>Learn some ghostly Chicago history while ma...   
28  <p>Do you need practice with your reading skil...   
29  <p>Join Mrs. Vicky for an afternoon of stories...   

                                          program_url virtual  \
0   https://chipublib.bibliocommons.com/events/615...   false   
1   https://chipublib.bibliocommons.com/events/612...    true   
2   https://chipublib.bibliocommons.com/events/612...    true   
3   https://chipublib.bibliocommons.com/events/613...   false   
4   https://chipublib.bibliocommons.com/events/613...   false   
5   https://chipublib.bibliocommons.com/events/610...    true   
6   https://chipublib.bibliocommons.com/events/614

In [6]:
df=df.astype({"language":'string',
             "audience":'string',
             "contact_name":'string'})

In [7]:
df['location_name'] = np.where(df["virtual"]=='true', 'null', df['location_name'])
df['meeting_type'] = np.where(df["virtual"]=='true', 'online', 'face_to_face')
df[['start_date','start_time']] = df['start_date'].str.split('T',expand=True)
df[['end_date','end_time']] = df['end_date'].str.split('T',expand=True)

In [8]:
df["contact_name"]=df["contact_name"].str.split(']',1,expand=True)
df['contact_name'] = df['contact_name'].str.replace(r'<[^<>]*>', '', regex=True)
df['contact_name'] = df['contact_name'].str.replace('[','')
df['contact_name'] = df['contact_name'].str.replace(']','')
df["contact_name"]=df["contact_name"].str.split('+',1,expand=True)

In [9]:
df['contact_phone'] = df['contact_phone'].str.replace('+','')
df['contact_phone'] = df['contact_phone'].str.replace('1-','')
df['contact_phone'] = df['contact_phone'].str.replace('-','')

In [10]:
df

program_name  \
0                         Grab and Go: Paper Rose Craft   
1                                          Toddler Time   
2                                          Book Zoomies   
3     The Art of Storytelling with Pixar: In Person ...   
4                                  Preschool Story Time   
...                                                 ...   
1324                                     Books 'n Babes   
1325                                     Books 'n Babes   
1326                                     Books 'n Babes   
1327  Law at the Library: Wills, Trusts and Estate P...   
1328                 Adult Book Club: Deacon King Kong   

                                    program_description  \
0     <p>In celebration of Latinx History Month come...   
1     <p>Join the staff of the Thomas Hughes Childre...   
2     <p>Book Zoomies presents funny books, silly so...   
3     <p><strong>THE ART </strong>OF STORYTELLING LE...   
4     <p>Ms. April from the Blackstone Branch will s...   
...                                                 ...   
1324  <p>Come one, come all, to our fun story time f...   
1325  <p>Come one, come all, to our fun story time f...   
1326  <p>Come one, come all, to our fun story time f...   
1327  <figure><img src="https://chipublib.bibliocomm...   
1328  <p>This month, we're reading&nbsp;<a id="ember...   

                                            program_url virtual  \
0     https://chipublib.bibliocommons.com/events/615...   false   
1     https://chipublib.bibliocommons.com/events/612...    true   
2     https://chipublib.bibliocommons.com/events/612...    true   
3     https://chipublib.bibliocommons.com/events/613...   false   
4     https://chipublib.bibliocommons.com/events/613...   false   
...                                                 ...     ...   
1324  https://chipublib.bibliocommons.com/events/615...    true   
1325  https://chipublib.bibliocommons.com/events/615...    true   
1326  https://chipublib.bibliocommons.com/events/615...    true   
1327  https://chipublib.bibliocommons.com/events/611...    true   
1328  https://chipublib.bibliocommons.com/events/60e...    true   

                                       registration_url  start_date  \
0     https://chipublib.bibliocommons.com/events/615...  2021-10-07   
1     https://chipublib.bibliocommons.com/events/612...  2021-10-07   
2     https://chipublib.bibliocommons.com/events/612...  2021-10-07   
3     https://chipublib.bibliocommons.com/events/613...  2021-10-07   
4     https://chipublib.bibliocommons.com/events/613...  2021-10-07   
...                                                 ...         ...   
1324  https://chipublib.bibliocommons.com/events/615...  2022-02-28   
1325  https://chipublib.bibliocommons.com/events/615...  2022-03-14   
1326  https://chipublib.bibliocommons.com/events/615...  2022-03-28   
1327  https://chipublib.bibliocommons.com/events/611...  2022-03-29   
1328  https://chipublib.bibliocommons.com/events/60e...  2022-03-31   

        end_date                program                          category  \
0     2021-10-07         Latinx History            Crafts, Games and Play   
1     2021-10-07                   null                        Story Time   
2     2021-10-07                   null                        Story Time   
3     2021-10-07  One Book, One Chicago  Continuing Education and College   
4     2021-10-07                   null                        Story Time   
...          ...                    ...                               ...   
1324  2022-02-28                   null                        Story Time   
1325  2022-03-14                   null                        Story Time   
1326  2022-03-28                   null                        Story Time   
1327  2022-03-29     Law at the Library           Business, Law and Money   
1328  2022-03-31                   null                        Book Clubs   

                                          

In [11]:
# def cpl_programs(url):
#     program_list=[]
#     try:
#         r=requests.get(url)
#         soup=BeautifulSoup(r.content, features='xml')
# #         return print('CPL scrape successful: ',r.status_code)
#         programs = soup.findAll('item')
    
#         for p in programs:
#             title=p.find('title').text
#             link=p.find('link').text
#             start_date=p.find('bc:start_date_local').text
            
#             program={'title':title,
#                     'link':link,
#                     'start date':start_date
#                     }
#             program_list.append(program)
        

#         return print(program_list)
#     except Exception as e:
#         print('FAILED. See exception: ')
#         print(e)
        


In [12]:
# print('Starting scrape')
# cpl_programs(url)
# print('Finished')

In [13]:
# df['category'] = df['category'].str.replace('Crafts, Games and Play', '1')
# df['category'] = df['category'].str.replace('Story Time', '2')
# df['category'] = df['category'].str.replace('Continuing Education and College', '3')
# df['category'] = df['category'].str.replace('Celebrations', '4')
# df['category'] = df['category'].str.replace('Jobs and Careers', '5')
# df['category'] = df['category'].str.replace('Book Clubs', '6')
# df['category'] = df['category'].str.replace('Computers and Technology', '7')

In [14]:
cat_list=df['category'].unique()

In [15]:
len(cat_list)

18

In [16]:
MCMF_list=['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18']

In [17]:
ids = {'lib_cats':cat_list,
      'MCMF_cat':MCMF_list}

ids = dict(zip(ids['lib_cats'], ids['MCMF_cat']))

In [18]:
for old, new in ids.items():
    df['category'] = df['category'].str.replace(old, new, regex=False)

In [19]:
df['language'] = df['language'].str.replace(r'<[^<>]*>', '', regex=True)
df['language'] = df['language'].str.replace('[','')
df['language'] = df['language'].str.replace(']','')

In [20]:
df['audience'] = df['audience'].str.replace(r'<[^<>]*>', '', regex=True)
df['audience'] = df['audience'].str.replace('[','')
df['audience'] = df['audience'].str.replace(']','')

In [21]:
df['program_description'] = df['program_description'].str.replace(r'<[^<>]*>', '', regex=True)

In [22]:
df

program_name  \
0                         Grab and Go: Paper Rose Craft   
1                                          Toddler Time   
2                                          Book Zoomies   
3     The Art of Storytelling with Pixar: In Person ...   
4                                  Preschool Story Time   
...                                                 ...   
1324                                     Books 'n Babes   
1325                                     Books 'n Babes   
1326                                     Books 'n Babes   
1327  Law at the Library: Wills, Trusts and Estate P...   
1328                 Adult Book Club: Deacon King Kong   

                                    program_description  \
0     In celebration of Latinx History Month come&nb...   
1     Join the staff of the Thomas Hughes Children's...   
2     Book Zoomies presents funny books, silly songs...   
3     THE ART OF STORYTELLING LEARNING CIRCLES How w...   
4     Ms. April from the Blackstone Branch will shar...   
...                                                 ...   
1324  Come one, come all, to our fun story time for ...   
1325  Come one, come all, to our fun story time for ...   
1326  Come one, come all, to our fun story time for ...   
1327  Each Law at the Library program features a pre...   
1328  This month, we're reading&nbsp;Deacon King Kon...   

                                            program_url virtual  \
0     https://chipublib.bibliocommons.com/events/615...   false   
1     https://chipublib.bibliocommons.com/events/612...    true   
2     https://chipublib.bibliocommons.com/events/612...    true   
3     https://chipublib.bibliocommons.com/events/613...   false   
4     https://chipublib.bibliocommons.com/events/613...   false   
...                                                 ...     ...   
1324  https://chipublib.bibliocommons.com/events/615...    true   
1325  https://chipublib.bibliocommons.com/events/615...    true   
1326  https://chipublib.bibliocommons.com/events/615...    true   
1327  https://chipublib.bibliocommons.com/events/611...    true   
1328  https://chipublib.bibliocommons.com/events/60e...    true   

                                       registration_url  start_date  \
0     https://chipublib.bibliocommons.com/events/615...  2021-10-07   
1     https://chipublib.bibliocommons.com/events/612...  2021-10-07   
2     https://chipublib.bibliocommons.com/events/612...  2021-10-07   
3     https://chipublib.bibliocommons.com/events/613...  2021-10-07   
4     https://chipublib.bibliocommons.com/events/613...  2021-10-07   
...                                                 ...         ...   
1324  https://chipublib.bibliocommons.com/events/615...  2022-02-28   
1325  https://chipublib.bibliocommons.com/events/615...  2022-03-14   
1326  https://chipublib.bibliocommons.com/events/615...  2022-03-28   
1327  https://chipublib.bibliocommons.com/events/611...  2022-03-29   
1328  https://chipublib.bibliocommons.com/events/60e...  2022-03-31   

        end_date                program category  \
0     2021-10-07         Latinx History        1   
1     2021-10-07                   null        2   
2     2021-10-07                   null        2   
3     2021-10-07  One Book, One Chicago        3   
4     2021-10-07                   null        2   
...          ...                    ...      ...   
1324  2022-02-28                   null        2   
1325  2022-03-14                   null        2   
1326  2022-03-28                   null        2   
1327  2022-03-29     Law at the Library       13   
1328  2022-03-31                   null        6   

                            audience  ...          location_address  \
0                               Kids  ...         6 S. Hoyne Avenue   
1                           Toddlers  ...                 None None   
2     Babies, Preschoolers, Toddlers  ...                 None None   
3                             Adults  ...      2708 S. Pul

In [23]:
df.to_csv('test_run.csv')

In [24]:
r1,r2=-2,4

In [25]:
np.arange(r1,r2+1,1)

array([-2, -1,  0,  1,  2,  3,  4])

In [26]:
babymin,babymax=0,2
babyrange=np.arange(babymin,babymax+1,1)
babyrange

array([0, 1, 2])

In [27]:
toddlermin,toddlermax=1,3
toddlerrange=np.arange(toddlermin,toddlermax+1,1)
toddlerrange

array([1, 2, 3])

In [28]:
prekmin,prekmax=2,4
prekrange=np.arange(prekmin,prekmax+1,1)
prekrange

array([2, 3, 4])

In [29]:
np.append(np.append(babyrange,prekrange),toddlerrange)

array([0, 1, 2, 2, 3, 4, 1, 2, 3])